### ISSUE TITLE
node-mysql版本问题

### ISSUE THREAD

**Issue by soulwu** [BetterJS/badjs-web#15]
`badjs-web`中指定了`node-mysql`的版本为`2.0.0-rc2`，不是使用最新的版本
我本地使用的percona-5.7.13-6，发现在连接mysql的时候，会报错
```
/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:17
       				throw err;
       				^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'badjs'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:32:14)
    at Handshake.ErrorPacket (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:67:18)
    at Protocol._parsePacket (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:186:24)
    at Parser.write (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:36:16)
    at Socket.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    --------------------
    at Handshake.Sequence (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:15:20)
    at new Handshake (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:9:12)
    at Protocol.handshake (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:41:50)
    at Connection.connect (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/mysql/lib/Connection.js:73:18)
    at Driver.connect (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/Drivers/DML/mysql.js:65:10)
    at Object.exports.connect (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:122:10)
    at Object.module.exports (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:12:6)
    at Object.exports.express (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:38:30)
    at Object.<anonymous> (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/workflow/ExpressInitWorker.js:35:13)
    at Module._compile (module.js:541:32)
```

查了下，`node-mysql`在后续的版本中修复了该问题，好像是2.1.1版本的changelog里有类似的，不确认是否是这个问题

我修改为使用最新的`node-mysql`后，该问题解决

**Comment by yorts52** [comment]
已更新
