### ISSUE TITLE
orm版本问题

### ISSUE THREAD

**Issue by soulwu** [BetterJS/badjs-web#16]
目前指定了`orm`的版本为`2.1.3`，但是发现一个致命的错误
该版本中读取配置`opts`里的debug和pool选项时，直接使用了`hasOwnProperty`，导致报错，程序无法正常执行。错误信息如下：
```
/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:17
       				throw err;
       				^

Error: CONNECTION_PROTOCOL_NOT_SUPPORTED
    at Object.defineProperty.value (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ErrorCodes.js:20:13)
    at Object.exports.connect (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:135:32)
    at Object.module.exports (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:12:6)
    at Object.exports.express (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:38:30)
    at Object.<anonymous> (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/workflow/ExpressInitWorker.js:35:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

这里是被包装过后的错误信息，不是很准确，我把实际的错误信息打印出来了：
```
TypeError: opts.query.hasOwnProperty is not a function
    at extractOption (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:393:33)
    at Object.exports.connect (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:112:18)
    at Object.module.exports (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:12:6)
    at Object.exports.express (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:38:30)
    at Object.<anonymous> (/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/workflow/ExpressInitWorker.js:35:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
/Users/soulwu/Documents/work/git/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:17
```

需要升级`orm`版本到`2.1.25`以上，该版本中有对这段相关代码的[修复 ](https://github.com/dresende/node-orm2/pull/639/files)

**Comment by soulwu** [comment]
发现orm不支持最新的node版本，需要把node退回到4才能正常使用，这个issue可以关闭了～

**Comment by yorts52** [comment]
建议使用 LTS 版本
