### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by x4storm** [BetterJS/badjs-web#23]
```
[2017-01-19 11:10:53.086] [DEBUG] [default] - query url : http://127.0.0.1:9000/query
internal/child_process.js:289
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.<anonymous> (/Users/huangzhi/Service/badjs/badjs-installer/badjs-web/node_modules/node-highcharts-exporting/index.js:18:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by yorts52** [comment]
请提供 node 版本号等相关信息，初步判断是你使用的 node 版本太低了

**Comment by x4storm** [comment]
node 是 6.9.1 我一直用的是 LTS的最高版本。
是 badjs-web 模块的报错

**Comment by yorts52** [comment]
@caihuiji 
报错的地方是 https://github.com/caihuiji/node-highcharts-exporting/blob/1e4d5e82afbfa3dcac9c4d93d09a38b26c89849d/index.js#L18

因为 phantomjs.path 是 null，参考这个 issue： https://github.com/Medium/phantomjs/issues/533

建议使用如下命令重新安装：

```bash
rm -rf node_modules
PHANTOMJS_CDNURL=http://npm.taobao.org/mirrors/phantomjs/ npm install
```

到这里这个问题已经解决，但是这里依赖的 https://github.com/caihuiji/node-highcharts-exporting 需要升级，参考：https://github.com/caihuiji/node-highcharts-exporting/issues/5

**Comment by caihuiji** [comment]
已经增加检测和提示，
主要是国内下载 phantomjs 经常失败，造成 node-hightcharts-exporting 加载 phantomjs 失败

**Comment by freefcw** [comment]
still appear this problem:


/data/web/badjs-web/node_modules/.0.0.9@node-highcharts-exporting/index.js:22
    throw new Error("can no found phantomjs , see https://github.com/BetterJS/badjs-web/issues/23")
    ^

Error: can no found phantomjs , see https://github.com/BetterJS/badjs-web/issues/23
    at Object.<anonymous> (/data/web/badjs-web/node_modules/.0.0.9@node-highcharts-exporting/index.js:22:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/web/badjs-web/service/EmailService.js:13:17)
    at Module._compile (module.js:570:32)


$ uname -a
Linux srv120 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


$ node --version
v6.11.1

**Comment by gebilaoman** [comment]
依旧是报错
